---
title: "TimScript"
author: "Tianqi(Tim)"
date: "6/14/2021"
output: html_document
---

```{r Libraries, include=FALSE}
#packages
if (!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)
if (!require("ggpubr")) install.packages("ggpubr")
library(ggpubr)
if (!require("rstatix")) install.packages("rstatix")
library(rstatix)
if (!require("car")) install.packages("car")
library(car)
if (!require("broom")) install.packages("broom")
library(broom)
if (!require("MASS")) install.packages("MASS")
library(MASS)

```


```{r}
#sort data
TOMM40 <- read.csv("https://raw.githubusercontent.com/Kakashi-sensei/T40_rsfMRI/main/UKB_Jan_27_2020.csv", header=TRUE)

TOMM40 <- TOMM40[as.numeric(rownames(unique(data.frame(TOMM40$EID)[1]))),]

colnames(TOMM40)[colnames(TOMM40)=="RecruitmentAge"] <- "Age"

TOMM40s <- select(TOMM40, EID, Dx_CNSDisease, Dx_Dementia, Dx_CeVDisease, Sex, Age, Education, SocialClass, APOE_all, FamilyHistoryAD, T40_Gcar, rsfMRI_Component1, rsfMRI_Component2, rsfMRI_Component3, rsfMRI_Component4, rsfMRI_Component5, rsfMRI_Component6, rsfMRI_Component7, rsfMRI_Component8, rsfMRI_Component9, rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18, rsfMRI_Component19, rsfMRI_Component20, rsfMRI_Component21)

TOMM40s$SocialClass <- as.factor(TOMM40s$SocialClass)
TOMM40s$FamilyHistoryAD <- as.factor(TOMM40s$FamilyHistoryAD)
levels(TOMM40s$FamilyHistoryAD) <- c("Neg", "Pos")
TOMM40s$Education<- as.factor(TOMM40s$Education)
TOMM40s$Sex <- factor(TOMM40s$Sex)

#MANOVA

if (!require("psych")) install.packages("psych")
library(psych)
if (!require("effects")) install.packages("effects")
library(effects)
rm(TOMM40)
rm(packages)
rm(ipak)
#write.csv(TOMM40s,file="C:/Users/46554/github/R/T40_rsfMRI/T40_rsfMRI/TOMM40s.csv")

# test assumption: perform MANOVA to see if the interaction term of the covariate and the group variable is significant#

# if interaction term insignificant then assumption of parallel slopes holds#

outcome = cbind (TOMM40s$rsfMRI_Component1, TOMM40s$rsfMRI_Component2, TOMM40s$rsfMRI_Component3, TOMM40s$rsfMRI_Component4, TOMM40s$rsfMRI_Component5, TOMM40s$rsfMRI_Component6, TOMM40s$rsfMRI_Component7, TOMM40s$rsfMRI_Component8, TOMM40s$rsfMRI_Component9, TOMM40s$rsfMRI_Component10, TOMM40s$rsfMRI_Component11, TOMM40s$rsfMRI_Component12, TOMM40s$rsfMRI_Component13, TOMM40s$rsfMRI_Component14, TOMM40s$rsfMRI_Component15, TOMM40s$rsfMRI_Component16, TOMM40s$rsfMRI_Component17, TOMM40s$rsfMRI_Component18, TOMM40s$rsfMRI_Component19, TOMM40s$rsfMRI_Component20, TOMM40s$rsfMRI_Component21)

model = manova (outcome ~ Sex + T40_Gcar + Sex*T40_Gcar, data=TOMM40s) #one-way MANOVA, Sex is for Groups, and T40_Gcar is for covariate
summary(model, test="Wilks", type = "III")
# Sex:T40_Gcar     1 0.99826    0.905     21  10911  0.584282
# it passes the test
summary(model, test="Pillai", type = "III")
summary(model, test="Hotelling", type = "III")
summary(model, test="Roy", type = "III")

model = manova (outcome ~ Education + T40_Gcar + Education*T40_Gcar, data=TOMM40s) #one-way MANOVA, Education is for Groups, and T40_Gcar is for covariate
summary(model, test="Wilks", type = "III")

model = manova (outcome ~ FamilyHistoryAD + T40_Gcar + FamilyHistoryAD*T40_Gcar, data=TOMM40s) #one-way MANOVA, family history is for Groups, and T40_Gcar is for covariate
summary(model, test="Wilks", type = "III")

model = manova (outcome ~ SocialClass + T40_Gcar + SocialClass*T40_Gcar, data=TOMM40s) #one-way MANOVA, social class is for Groups, and T40_Gcar is for covariate
summary(model, test="Wilks", type = "III")


# test assumption: Homoscedosticity of regression slopes (check by comparing MSE from separate group regressions)#
modelA = aov(rsfMRI_Component1~T40_Gcar + Sex, data= TOMM40s)#T40_Gcar is for covariate
summary(modelA, type="III")
#T40_Gcar is not significant here(0.569)

adjmeanA = effect("Sex", modelA, se = TRUE, xlevels=2)
summary(adjmeanA)
# Sex effect   Female 2.522368    Male 2.470038

adjmeanA$se

modelB = aov(rsfMRI_Component2~T40_Gcar + Sex, data= TOMM40s)#T40_Gcar is for covariate
summary(modelB, type="III")
#T40_Gcar is not significant here(0.0648)

adjmeanB = effect("Sex", modelB, se = TRUE, xlevels=2)
summary(adjmeanB)
# Sex effect   Female 2.050129    Male 2.113963

adjmeanB$se

modelC = aov(rsfMRI_Component3~T40_Gcar + Sex, data= TOMM40s)#T40_Gcar is for covariate
summary(modelC, type="III")#T40_Gcar is not significant here(0.795748)

model4 = aov(rsfMRI_Component4~T40_Gcar + Sex, data= TOMM40s)#T40_Gcar is for covariate
summary(model4, type="III")#T40_Gcar is not significant here(0.104); Sex is not significant too(0.899)

#Homoscedosticity of regression slopes could be violated here.

fit <- manova(outcome ~ T40_Gcar, data=TOMM40s)
summary(fit, test="Pillai")
# p=0.01009

#MANCOVA test
if (!require("jmv")) install.packages("jmv")
library(jmv)

fit <- mancova(data = TOMM40s, deps = vars(rsfMRI_Component1,rsfMRI_Component2), factors = Sex, covs = Age)
#Error in mvnormtest::mshapiro.test(dataDeps) : sample size must be between 3 and 5000

modelx = aov(outcome~T40_Gcar*Age + Sex + FamilyHistoryAD + SocialClass, data= TOMM40s)

summary(modelx, type="III")

rm(list = ls())
```

```{r}
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE)
    sapply(pkg, require, character.only = TRUE)
}

# usage
packages <- c("plyr", "dplyr", "stringr", "reshape2","ggplot2","glmnet","corrplot","data.table","lm.beta","knitr","jtools","interactions","sandwich", "emmeans","jmv","heplots","sjstats","formatR")
ipak(packages)
```



```{r}
#6/21 rerun
DMS <- read.csv("https://raw.githubusercontent.com/Kakashi-sensei/T40_rsfMRI/main/TOMM40s.csv", header=TRUE)
DMS <- DMS[as.numeric(rownames(unique(data.frame(DMS$EID)[1]))),]

colnames(DMS)[colnames(DMS)=="RecruitmentAge"] <- "Age"

require(jmv)

DMRS <- DMS

DMRS$FamilyHistoryAD <- as.factor(DMRS$FamilyHistoryAD)
levels(DMRS$FamilyHistoryAD) <- c("Neg", "Pos")
DMRS$Education<- as.factor(DMRS$Education)
DMRS$Sex <- factor(DMRS$Sex)
levels(DMRS$Sex)
levels(DMRS$Sex) <- c("Female", "Male")
DMRS$Sex <- relevel(DMRS$Sex, ref="Male") 

DMRS5$T40_Gcar <- as.factor(DMRS5$T40_Gcar)
DMRS$Agecat<-cut(DMRS$Age, c(39,64,100),labels=c(1:2))
levels(DMRS$Agecat) <- c("Middle Age","Old Age")
#summary(DMRS$Agecat)
DMRS <- na.omit(DMRS)

DMRS <- DMRS[DMRS$Dx_CNSDisease!="1",]
DMRS <- DMRS[DMRS$Dx_CeVDisease!="1",]
DMRS <- DMRS[DMRS$Dx_Dementia!="1",]
#After excluding these conditions -> 9961 obs

DMRS2 <- DMRS[complete.cases(DMRS),] #10921 obs
levels(DMRS2$T40_Gcar) <- c("Non-Carrier", "Carrier")

#1.) E2’s vs. E3’s vs. E4’s
#—E2/E2 + E2/E3 vs. E3/E3 vs. E2/E4 + E3/E4 + E4/E4
DMRS2  <- DMRS[DMRS$APOE_all %in% c("e2/e2","e2/e3","e3/e3","e4/e3","e4/e4"),] #8640
DMRS2 <- DMRS2[complete.cases(DMRS2),] #8222 obs

DMRS3 <- DMRS2
levels(DMRS3$T40_Gcar) <- c("Non-Carrier", "Carrier")

nu <- data.frame(lapply(DMRS3,function(x) {x <- gsub("e2/e2","E2",x,fixed=TRUE)}))
nu <- data.frame(lapply(nu,function(x) {x <- gsub("e2/e3","E2",x,fixed=TRUE)}))
nu <- data.frame(lapply(nu,function(x) {x <- gsub("e3/e3","E3",x,fixed=TRUE)}))
nu <- data.frame(lapply(nu,function(x) {x <- gsub("e4/e3","E4",x,fixed=TRUE)}))
nu <- data.frame(lapply(nu,function(x) {x <- gsub("e4/e4","E4",x,fixed=TRUE)}))
nu$APOE_all <- as.factor(nu$APOE_all) # Scott's method 8222 obs

nu$Age <- as.numeric(nu$Age)
nu$rsfMRI_Component1 <- as.numeric(nu$rsfMRI_Component1)
nu$rsfMRI_Component2 <- as.numeric(nu$rsfMRI_Component2)
nu$rsfMRI_Component3 <- as.numeric(nu$rsfMRI_Component3)
nu$rsfMRI_Component4 <- as.numeric(nu$rsfMRI_Component4)
nu$rsfMRI_Component5 <- as.numeric(nu$rsfMRI_Component5)
nu$rsfMRI_Component6 <- as.numeric(nu$rsfMRI_Component6)
nu$rsfMRI_Component7 <- as.numeric(nu$rsfMRI_Component7)
nu$rsfMRI_Component8 <- as.numeric(nu$rsfMRI_Component8)
nu$rsfMRI_Component9 <- as.numeric(nu$rsfMRI_Component9)
nu$rsfMRI_Component10 <- as.numeric(nu$rsfMRI_Component10)
nu$rsfMRI_Component11 <- as.numeric(nu$rsfMRI_Component11)
nu$rsfMRI_Component12 <- as.numeric(nu$rsfMRI_Component12)
nu$rsfMRI_Component13 <- as.numeric(nu$rsfMRI_Component13)
nu$rsfMRI_Component14 <- as.numeric(nu$rsfMRI_Component14)
nu$rsfMRI_Component15 <- as.numeric(nu$rsfMRI_Component15)
nu$rsfMRI_Component16 <- as.numeric(nu$rsfMRI_Component16)
nu$rsfMRI_Component17 <- as.numeric(nu$rsfMRI_Component17)
nu$rsfMRI_Component18 <- as.numeric(nu$rsfMRI_Component18)
nu$rsfMRI_Component19 <- as.numeric(nu$rsfMRI_Component19)
nu$rsfMRI_Component20 <- as.numeric(nu$rsfMRI_Component20)
nu$rsfMRI_Component21 <- as.numeric(nu$rsfMRI_Component21)

#write.csv(nu,file="C:/Users/46554/github/R/T40_rsfMRI/T40_rsfMRI/nu.csv")

nu <- read.csv("https://raw.githubusercontent.com/Kakashi-sensei/T40_rsfMRI/main/nu.csv", header=TRUE)

fit <- mancova(data = nu4, deps = vars(rsfMRI_Component1,rsfMRI_Component2, rsfMRI_Component3, rsfMRI_Component4, rsfMRI_Component5, rsfMRI_Component6, rsfMRI_Component7, rsfMRI_Component8, rsfMRI_Component9, rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18, rsfMRI_Component19, rsfMRI_Component20, rsfMRI_Component21), factors = T40_Gcar, covs = Age)

nu4 <- nu[nu$APOE_all %in% c("E4"),]

fit

```





```{r MANOVA, include=FALSE}
rm(list = ls())

nu <- read.csv("https://raw.githubusercontent.com/Kakashi-sensei/T40_rsfMRI/main/nu.csv", header=TRUE)


NU <-nu

DMRS5 <- nu[nu$APOE_all %in% c("E2","E3","E4"),]
DMRS5$APOE_all <- revalue(DMRS5$APOE_all, c("E2"="E4-", "E3"="E4-","E4"="E4+"))

DMRS6 <- DMRS5[DMRS5$APOE_all %in% c("E4+"),]


#APOE without T40 
res <- manova(cbind(rsfMRI_Component1,rsfMRI_Component2,rsfMRI_Component3,rsfMRI_Component4,rsfMRI_Component5,rsfMRI_Component6,rsfMRI_Component7,rsfMRI_Component8,rsfMRI_Component9,rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18,rsfMRI_Component19,rsfMRI_Component20,rsfMRI_Component21) ~ APOE_all,data=nu)
summary(res)

res2 <- manova(cbind(rsfMRI_Component1,rsfMRI_Component2,rsfMRI_Component3,rsfMRI_Component4,rsfMRI_Component5,rsfMRI_Component6,rsfMRI_Component7,rsfMRI_Component8,rsfMRI_Component9,rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18,rsfMRI_Component19,rsfMRI_Component20,rsfMRI_Component21) ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD,data=nu)
summary(res2)

#interactions
asr <- manova(cbind(rsfMRI_Component1,rsfMRI_Component2,rsfMRI_Component3,rsfMRI_Component4,rsfMRI_Component5,rsfMRI_Component6,rsfMRI_Component7,rsfMRI_Component8,rsfMRI_Component9,rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18,rsfMRI_Component19,rsfMRI_Component20,rsfMRI_Component21) ~ APOE_all*Sex+Age+Education+SocialClass+FamilyHistoryAD,data=nu)
summary(asr) #ns

aar <- manova(cbind(rsfMRI_Component1,rsfMRI_Component2,rsfMRI_Component3,rsfMRI_Component4,rsfMRI_Component5,rsfMRI_Component6,rsfMRI_Component7,rsfMRI_Component8,rsfMRI_Component9,rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18,rsfMRI_Component19,rsfMRI_Component20,rsfMRI_Component21) ~ APOE_all*Age+Sex+Education+SocialClass+FamilyHistoryAD,data=nu)
summary(aar) #ns


#T40 - all participants
res <- manova(cbind(rsfMRI_Component1,rsfMRI_Component2,rsfMRI_Component3,rsfMRI_Component4,rsfMRI_Component5,rsfMRI_Component6,rsfMRI_Component7,rsfMRI_Component8,rsfMRI_Component9,rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18,rsfMRI_Component19,rsfMRI_Component20,rsfMRI_Component21) ~ T40_Gcar,data=DMRS5)
summary(res)

res2 <- manova(cbind(rsfMRI_Component1,rsfMRI_Component2,rsfMRI_Component3,rsfMRI_Component4,rsfMRI_Component5,rsfMRI_Component6,rsfMRI_Component7,rsfMRI_Component8,rsfMRI_Component9,rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18,rsfMRI_Component19,rsfMRI_Component20,rsfMRI_Component21) ~ T40_Gcar+APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD,data=DMRS5)
summary(res2) #trending T40

#interactions
res3 <- manova(cbind(rsfMRI_Component1,rsfMRI_Component2,rsfMRI_Component3,rsfMRI_Component4,rsfMRI_Component5,rsfMRI_Component6,rsfMRI_Component7,rsfMRI_Component8,rsfMRI_Component9,rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18,rsfMRI_Component19,rsfMRI_Component20,rsfMRI_Component21) ~ T40_Gcar*Sex+APOE_all+Age+Education+SocialClass+FamilyHistoryAD,data=DMRS5)
summary(res3) #ns int

res4 <- manova(cbind(rsfMRI_Component1,rsfMRI_Component2,rsfMRI_Component3,rsfMRI_Component4,rsfMRI_Component5,rsfMRI_Component6,rsfMRI_Component7,rsfMRI_Component8,rsfMRI_Component9,rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18,rsfMRI_Component19,rsfMRI_Component20,rsfMRI_Component21) ~ T40_Gcar*Age+APOE_all+Sex+Education+SocialClass+FamilyHistoryAD,data=DMRS5)
summary(res4) #ns int


#APOE4 only
res5 <- manova(cbind(rsfMRI_Component1,rsfMRI_Component2,rsfMRI_Component3,rsfMRI_Component4,rsfMRI_Component5,rsfMRI_Component6,rsfMRI_Component7,rsfMRI_Component8,rsfMRI_Component9,rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18,rsfMRI_Component19,rsfMRI_Component20,rsfMRI_Component21) ~ T40_Gcar,data=DMRS6)
summary(res5) #ns

res6 <- manova(cbind(rsfMRI_Component1,rsfMRI_Component2,rsfMRI_Component3,rsfMRI_Component4,rsfMRI_Component5,rsfMRI_Component6,rsfMRI_Component7,rsfMRI_Component8,rsfMRI_Component9,rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18,rsfMRI_Component19,rsfMRI_Component20,rsfMRI_Component21) ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD,data=DMRS6)
summary(res6) #ns

#interactions
res7 <- manova(cbind(rsfMRI_Component1,rsfMRI_Component2,rsfMRI_Component3,rsfMRI_Component4,rsfMRI_Component5,rsfMRI_Component6,rsfMRI_Component7,rsfMRI_Component8,rsfMRI_Component9,rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18,rsfMRI_Component19,rsfMRI_Component20,rsfMRI_Component21) ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD,data=DMRS6)
summary(res7) #int ns

res8 <- manova(cbind(rsfMRI_Component1,rsfMRI_Component2,rsfMRI_Component3,rsfMRI_Component4,rsfMRI_Component5,rsfMRI_Component6,rsfMRI_Component7,rsfMRI_Component8,rsfMRI_Component9,rsfMRI_Component10,rsfMRI_Component11,rsfMRI_Component12,rsfMRI_Component13,rsfMRI_Component14,rsfMRI_Component15,rsfMRI_Component16,rsfMRI_Component17,rsfMRI_Component18,rsfMRI_Component19,rsfMRI_Component20,rsfMRI_Component21) ~ T40_Gcar*Age+Sex+Education+SocialClass+FamilyHistoryAD,data=DMRS6)
summary(res8) #int ns
```

```{r APOE without T40}
fit <- aov(rsfMRI_Component21 ~  T40_Gcar*Sex + T40_Gcar + Agecat + Sex + Education +
SocialClass + FamilyHistoryAD + APOE_all, data = DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component1 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component2 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component3 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component3 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise",adjust="Bonferroni")

fit <- aov(rsfMRI_Component4 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component5 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component5 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni") #ns

fit <- aov(rsfMRI_Component6 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component6 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component7 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component7 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component8 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component8 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component9 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component9 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component10 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component11 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component12 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component13 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component13 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component14 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component14 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, adjust="Bonferroni")

fit <- aov(rsfMRI_Component15 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component15 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component16 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component17 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component17 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component18 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component19 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component19 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni") #ns

fit <- aov(rsfMRI_Component20 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component20 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component21 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
summary(lm.beta(fit))
Anova(fit, type="II")

lm_out <- lm(rsfMRI_Component21 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")
```

```{r T40 Main Effects - ALL PARTICIPANTS }
fit <- aov(rsfMRI_Component1 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

lm_out <- lm(rsfMRI_Component1 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component2 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component3 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component3 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")


fit <- aov(rsfMRI_Component4 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component5 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component5 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")


fit <- aov(rsfMRI_Component6 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component6 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component7 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component7 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component8 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component9 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component10 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component11 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component12 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component13 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component14 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component15 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component16 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component17 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component17 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~T40_Gcar)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

lm_out <- lm(rsfMRI_Component17 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")


fit <- aov(rsfMRI_Component18 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component19 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component20 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component20 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

fit <- aov(rsfMRI_Component21 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component21 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")
```

```{r T40 * Sex - ALL PARTICIPANTS, include=FALSE}
levels(DMRS5$T40_Gcar)[levels(DMRS5$T40_Gcar)=='0'] = 'Non-Carrier'
levels(DMRS5$T40_Gcar)[levels(DMRS5$T40_Gcar)=='1'] = 'Carrier'

fit <- aov(rsfMRI_Component1 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")


fit <- aov(rsfMRI_Component2 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

lm_out <- lm(rsfMRI_Component2 ~ T40_Gcar*Sex+Age+SocialClass+Education+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~T40_Gcar+Sex)
post_hoc2 <- summary(post_hoc) %>%
    mutate(
        ymin=emmean-SE,
        ymax=emmean+SE,
    )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")
contrast(post_hoc, adjust="Bonferroni")

fit <- aov(rsfMRI_Component3 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component4 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component5 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component6 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component7 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component8 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")


fit <- aov(rsfMRI_Component9 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")
lm_out <- lm(rsfMRI_Component9 ~ T40_Gcar*Sex+Age+SocialClass+Education+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~T40_Gcar+Sex)
post_hoc2 <- summary(post_hoc) %>%
    mutate(
        ymin=emmean-SE,
        ymax=emmean+SE,
    )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")
contrast(post_hoc, adjust="Bonferroni")

fit <- aov(rsfMRI_Component10 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component11 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

lm_out <- lm(rsfMRI_Component11 ~ T40_Gcar*Sex+Age+SocialClass+Education+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~T40_Gcar+Sex)
post_hoc2 <- summary(post_hoc) %>%
    mutate(
        ymin=emmean-SE,
        ymax=emmean+SE,
    )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")
contrast(post_hoc, adjust="Bonferroni")

fit <- aov(rsfMRI_Component12 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

lm_out <- lm(rsfMRI_Component12 ~ T40_Gcar*Sex+Age+SocialClass+Education+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~T40_Gcar+Sex)
post_hoc2 <- summary(post_hoc) %>%
    mutate(
        ymin=emmean-SE,
        ymax=emmean+SE,
    )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")
contrast(post_hoc, adjust="Bonferroni")

fit <- aov(rsfMRI_Component13 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component14 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component15 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component16 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component17 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

lm_out <- lm(rsfMRI_Component17 ~ T40_Gcar*Sex+Age+SocialClass+Education+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~T40_Gcar+Sex)
post_hoc2 <- summary(post_hoc) %>%
    mutate(
        ymin=emmean-SE,
        ymax=emmean+SE,
    )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")
contrast(post_hoc, adjust="Bonferroni")

fit <- aov(rsfMRI_Component18 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

lm_out <- lm(rsfMRI_Component18 ~ T40_Gcar*Sex+Age+SocialClass+Education+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~T40_Gcar+Sex)
post_hoc2 <- summary(post_hoc) %>%
    mutate(
        ymin=emmean-SE,
        ymax=emmean+SE,
    )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")
contrast(post_hoc, adjust="Bonferroni")

fit <- aov(rsfMRI_Component19 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component20 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")

fit <- aov(rsfMRI_Component21 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
summary(lm.beta(fit))
Anova(fit, type="II")
```

```{r Figure 1, include=FALSE}

NU$APOE_all <- factor(NU$APOE_all, levels = c("E2", "E3", "E4"))

lm_out <- lm(rsfMRI_Component3 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

p1 <- ggplot(post_hoc2, aes(y=emmean, x=APOE_all))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab(NULL) +
  ylab(NULL) +
  ggtitle("Motor Planning (IC3)") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  coord_cartesian(ylim = c(2.00, 2.30))


p1 <- p1 + theme(text = element_text(size=16),
                strip.text.x = element_text(size=16),
                strip.text.y = element_text(size=16)) 
      
p1

lm_out <- lm(rsfMRI_Component6 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

p2 <- ggplot(post_hoc2, aes(y=emmean, x=APOE_all))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab(NULL) +
  ylab(NULL) +
  ggtitle("Left Auditory Processing (IC6)") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  coord_cartesian(ylim = c(1.85, 2.00))

p2 <- p2 + theme(text = element_text(size=16),
                strip.text.x = element_text(size=16),
                strip.text.y = element_text(size=16)) 

p2      

lm_out <- lm(rsfMRI_Component7 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

p3 <- ggplot(post_hoc2, aes(y=emmean, x=APOE_all))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab(NULL) +
  ylab(NULL) +
  ggtitle("Memory Consolidation (IC7)") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  coord_cartesian(ylim = c(1.80, 1.95))

p3 <- p3 + theme(text = element_text(size=16),
                strip.text.x = element_text(size=16),
                strip.text.y = element_text(size=16)) 
       

lm_out <- lm(rsfMRI_Component8 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

p4 <- ggplot(post_hoc2, aes(y=emmean, x=APOE_all))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab(NULL) +
  ylab(NULL) +
  ggtitle("Primary Visual (IC8)") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  coord_cartesian(ylim = c(2.50, 2.90))

p4 <- p4 + theme(text = element_text(size=16),
                strip.text.x = element_text(size=16),
                strip.text.y = element_text(size=16)) 

lm_out <- lm(rsfMRI_Component9 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

p5 <- ggplot(post_hoc2, aes(y=emmean, x=APOE_all))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab(NULL) +
  ylab(NULL) +
  ggtitle("Central Executive Function (IC9)") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  coord_cartesian(ylim = c(2.30, 2.70))

p5 <- p5 + theme(text = element_text(size=16),
                strip.text.x = element_text(size=16),
                strip.text.y = element_text(size=16)) 
        

lm_out <- lm(rsfMRI_Component15 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

p6 <- ggplot(post_hoc2, aes(y=emmean, x=APOE_all))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab(NULL) +
  ylab(NULL) +
  ggtitle("Cerebellum (IC15)") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  coord_cartesian(ylim = c(0.90, 1.05))

p6 <- p6 + theme(text = element_text(size=16),
                strip.text.x = element_text(size=16),
                strip.text.y = element_text(size=16)) 
       

lm_out <- lm(rsfMRI_Component20 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

p7 <- ggplot(post_hoc2, aes(y=emmean, x=APOE_all))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab(NULL) +
  ylab(NULL) +
  ggtitle("Posterior Default Mode (IC20)") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  coord_cartesian(ylim = c(1.75, 1.90))

p7 <- p7 + theme(text = element_text(size=16),
                strip.text.x = element_text(size=16),
                strip.text.y = element_text(size=16)) 
       

lm_out <- lm(rsfMRI_Component21 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

p8 <- ggplot(post_hoc2, aes(y=emmean, x=APOE_all))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab(NULL) +
  ylab(NULL) +
  ggtitle("Prefrontal (IC21)") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  coord_cartesian(ylim = c(1.50, 1.70))

p8 <- p8 + theme(text = element_text(size=16),
                strip.text.x = element_text(size=16),
                strip.text.y = element_text(size=16)) 
       

multiplot(p1, p5, p2, p6, p3, p7, p4, p8, cols=4)


lm_out <- lm(rsfMRI_Component20 ~ APOE_all+Age+Sex+Education+SocialClass+FamilyHistoryAD, data=NU)
post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

ggplot(post_hoc2, aes(y=emmean, x=APOE_all))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab("APOE Haplotype") +
  ylab("Posterior Default Mode Network (IC20)") +
  coord_cartesian(ylim = c(1.75, 1.90))
```

```{r Figure 2, include=FALSE}

levels(DMRS5$T40_Gcar)[levels(DMRS5$T40_Gcar)=='0'] = 'Non-G carrier'
levels(DMRS5$T40_Gcar)[levels(DMRS5$T40_Gcar)=='1'] = 'G carrier'

lm_out <- lm(rsfMRI_Component17 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~T40_Gcar)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

p1 <- ggplot(post_hoc2, aes(y=emmean, x=T40_Gcar))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab("TOMM40 Group") +
  ylab("Language Comprehension (IC17)") +
  coord_cartesian(ylim = c(1.75, 1.90))

post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

p2 <- ggplot(post_hoc2, aes(y=emmean, x=APOE_all))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab("APOE Status") +
  ylab("Language Comprehension (IC17)") +
  coord_cartesian(ylim = c(1.75, 1.90))

lm_out <- lm(rsfMRI_Component20 ~ T40_Gcar+Age+Sex+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~T40_Gcar)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

p3 <- ggplot(post_hoc2, aes(y=emmean, x=T40_Gcar))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab("TOMM40 Group") +
  ylab("Posterior Default Mode (IC20)") +
  coord_cartesian(ylim = c(1.75, 1.90))

post_hoc <- emmeans(lm_out, ~APOE_all)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="Bonferroni")

p4 <- ggplot(post_hoc2, aes(y=emmean, x=APOE_all))+
  geom_bar(stat="identity", position="dodge", fill="#80daeb")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab("APOE Status") +
  ylab("Posterior Default Mode (IC20)") +
  coord_cartesian(ylim = c(1.75, 1.90))

multiplot(p1, p3, p2, p4, cols=2)

#sex int
lm_out <- lm(rsfMRI_Component17 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~T40_Gcar+Sex)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise")

ggplot(post_hoc2, aes(y=emmean, x=T40_Gcar, fill=Sex))+
  geom_bar(stat="identity", position="dodge")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab("T40 Group") +
  ylab("Language Comprehension") +
  ggtitle("The Difference in Resting State fMRI per\nT40 category in UK Biobank cohort")+
    coord_cartesian(ylim = c(1.60, 2.00))

lm_out <- lm(rsfMRI_Component17 ~ T40_Gcar*Sex+Age+Education+SocialClass+FamilyHistoryAD+APOE_all, data=DMRS5)
post_hoc <- emmeans(lm_out, ~T40_Gcar+Sex)
post_hoc2 <- summary(post_hoc) %>%
  mutate(
    ymin=emmean-SE,
    ymax=emmean+SE,
  )
post_hoc2
contrast(post_hoc, "revpairwise", adjust="bonferroni")

ggplot(post_hoc2, aes(y=emmean, x=T40_Gcar, fill=Sex))+
  geom_bar(stat="identity", position="dodge")+
  geom_errorbar(width=0.25, position=position_dodge(0.9),
                aes(ymin=ymin, ymax=ymax))+theme_bw() + 
  xlab("TOMM40 Group") +
  ylab("Language Comprehension (IC17)") +
    coord_cartesian(ylim = c(1.60, 2.00))

```

